env:
  browser: true
  commonjs: true
extends:
  - 'eslint:recommended'
  - 'plugin:node/recommended'
parserOptions:
  ecmaVersion: 2018
rules:
  max-len:
    - warn
    - {
      code: 120
    }
  indent:
    - error
    - tab
    - {
      SwitchCase: 1
    }
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - double
  semi:
    - warn
    - always
  comma-dangle:
    - warn
    - never
  eqeqeq:
    - warn
    - always
  no-trailing-spaces:
    - error
  no-console:
    - off
  no-unused-vars:
    - warn
  no-useless-escape:
    - warn
  # Review the following

  # Node.js convention is to throw error to process root? Will errors bubble out of Discord client?
  no-process-exit:
    - warn
  # Deprecates based on latest version, any warnings need to check if latest is available in Node.js version used
  node/no-deprecated-api:
    - warn
