env:
  browser: true
  commonjs: true
extends:
  - 'eslint:recommended'
  - 'plugin:node/recommended'
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
