env:
  browser: true
  commonjs: true
extends:
  - 'eslint:recommended'
  - 'plugin:node/recommended'
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - tab
    - {
      SwitchCase: 1
    }
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - double
  semi:
    - warn
    - always
  comma-dangle:
    - warn
    - never
  eqeqeq:
    - warn
    - always
  no-trailing-spaces:
    - error
  no-console:
    - off
  no-unused-vars:
    - warn
  no-useless-escape:
    - warn

