version: "2.2"
services:
  app:
    container_name: app
    init: true
    restart: always
    build: .
    volumes:
      - ./data:/home/node/app/data
      - ./config.js:/home/node/app/config.js
      - ./src:/home/node/app/src
    command: ["node", "src/index.js"]
